title: Lerntagebuch Bibliotheks- und Archivinformatik
author: Sarina
description: > # this means to ignore newlines
  Lerntagebuch mit Blogartikeln über gesammelte Erfahrungen im Kurs Bibliotheks- und Archivinformatik FS2024

# social links
github_username:  fhstudentin # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
